main pull request
FrogOfJuly/CLI pull request #1
Opened 2021-02-13 15:53 UTC by FrogOfJuly

2021-02-26 00:44 UTC, aleksZubakov requested changes
Оставил комментарии, попозже еще приду что-нибудь функционально сломаю

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +class Arithm:
Какое-то странное именование, что значит `Arithm`? Это от слова arithmetic? Тогда я не понимаю причем оно тут

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +    }.get(name, Arithm)
Что-то очень странное здесь происходит. Зачем создавать словарь с одним элементом, чтобы его же и достать?

Если тут какая-то более сложна логика была, то все еще непонятно зачем объект на ровном месте лишний создавать и почему нельзя воспользоваться обычными ифами

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +    # return out
Не должно быть закомментированного кода

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +        return self.__str__()
[Почитайте](https://docs.python.org/3/reference/datamodel.html#object.__repr__) чем `__repr__` от `__str__` отличается, они немного про разное

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +        return mem, err
Плохо, что тут всегда какую-то строку `err` возвращаем, хотя она не нужна в большинстве случаев

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +                file = open(arg, 'r')
Странная идея открывать все файлы разом и держать их, обрабатывайте их по отдельности

И напоминаю про необходимость закрывать файлы, а также про существование менеджеров контекстов

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            except Exception:
Не надо ловить `Exception`, ловите наиболее конкретный

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +        complex_subst = re.compile("\$\{(.*?)\}")
А зачем `$` и скобочки экранировать?

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            lines = f.split('\n')
А откуда тут строка должна появиться?

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            out += name + " : " + " ".join([str(r) for r in vals]) + "\n"
Такая конкатенация за квадрат работает

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            out += line
Вообще говоря, плохая идея считывать весь файл в память, он мб очень большим

Вы ниже уже используете `StringIO`, попробуйте что-то подобное сделать для потока вывода и потока ошибок, а не возвращайте строки, тогда и файл можно будет не считывать целиком

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +        if len(file_args) == 0 and err == "":
`if not file_args and not err`

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            out += self.cat(arg)
Конкатенация за квадрат, но теперь еще и на потенциально больших файлах.

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +        "echo": Echo,
Ну вот тоже плохая идея создавать словарь при каждом вызове

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/cli.py
> +        line = line[:-1]
`rstrip()`?

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/cli.py
> +        if line == "":
`if not line`

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/parser.py
> +    id : /[a-zA-Z][a-zA-Z0-9_]*/
А зачем отдельный number, если он и так описывается в `id` целиком?

Вообще кажется, что грамматику можно сократить до двух правил, код ниже примерный, я его не тестировал:
```python
arithmetics: (string)(bop)(string)
bop: /[=]/
```

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/parser.py
> +        item, = items
???

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +        def perform_substitute(string: str, regexp, peel: Callable[[str], str]) -> str:
Здесь явно больше 79 символов, как этого требует [PEP 8](https://www.python.org/dev/peps/pep-0008/)

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            var = peel(match[0])
Лучше дать какое-то имя `match[0]`

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            new_string = re.sub(regexp,
Кажется, что эта штука тоже в цикл может уехать

2021-02-26 00:44 UTC, aleksZubakov commented on CLI/calls/calls.py
> +                                          peel=lambda s: s[2:-1])
Индексация по каким-то магическим индексам -- плохая идея

2021-02-26 00:44 UTC, aleksZubakov commented on tests/parse_test.py
> +def parse_test(input_text, verify: Callable) -> None:
Тестов маловато. Почему решили самопальные использовать, а не какие-нибудь уже существующие библиотеки?

2021-02-26 00:44 UTC, aleksZubakov commented on README.md
> +IO-loop   ->   lark parser
Хочется хоть какое-то описание увидеть, пока вижу только набор ничего не объясняющих стрелочек в readme :)

2021-02-26 14:53 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +class Arithm:
Чтобы как-то отделить его от остальных команд. Нам говорили на семинаре что можно overengineering делать. Этот класс для того чтобы туда вынести =, арифметику, $() и все остальное что не ложиться на pipe из команд

2021-02-26 14:54 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +    }.get(name, Arithm)
Ифами - уродливо, поэтому почему бы и не создать объект. Можно его вынести за функцию чтобы не создавать каждый раз заново, но это вроде не должно сильно на производительность влиять

2021-02-26 14:55 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +        return self.__str__()
Они одинаковые в этом случае

2021-02-26 14:56 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +        return mem, err
Каждая команда может выдать ошибку, так что это необходимо если не использовать потоки

2021-02-26 14:57 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +                file = open(arg, 'r')
действительно

2021-02-26 14:58 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +        complex_subst = re.compile("\$\{(.*?)\}")
Иначе питон ругается(Он и так ругается, поэтому я и экранировал их)

2021-02-26 14:59 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            out += line
Без честных потоков это сложно нормально сделать. Команда должна полностью выполниться до того как начнется выполнение другой, так что ее выход нужно будет хранить где-то. Можно через генераторы это все делать, но это как-то сложно пока

2021-02-26 15:00 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +        "echo": Echo,
Он же маленький. Это вместо ифов. Так же лучше выглядит с небольшим пенальти по производительности

2021-02-26 15:01 UTC, FrogOfJuly commented on CLI/parser.py
> +    id : /[a-zA-Z][a-zA-Z0-9_]*/
потому что у них разный смысл. Если будет арифметика, то это будет важно

2021-02-26 15:02 UTC, FrogOfJuly commented on CLI/parser.py
> +        item, = items
Это взято из туториал lark'а, он так парсит

2021-02-26 15:02 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +                                          peel=lambda s: s[2:-1])
именно поэтому она в отдельный аргумент вынесена

2021-02-26 15:03 UTC, FrogOfJuly commented on tests/parse_test.py
> +def parse_test(input_text, verify: Callable) -> None:
это не самопальные. Их распарсит pytest

2021-02-26 15:07 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +    }.get(name, Arithm)
словарь - на случай если будут другие команды чтобы на них ифы не писать

2021-02-27 16:07 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +class Arithm:
В самой абстракции нет ничего плохого, но overengineering != плохой нейминг, если что

Ну и кажется, что присваивание в переменную -- это не про арифметику

2021-02-27 16:10 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +        return self.__str__()
Ага, в этом как раз и проблема, что они одинаковые, хотя на `__repr__` все-таки привыкли какие-то дополнительные требования накладывать:

> This is typically used for debugging, so it is important that the representation is information-rich and unambiguous.

Т.е. это должно быть такое представление, по которому я в точности могу воссоздать объект где бы в логах он потом не появился. Как из какого-то напечатанного кортежа понять что он представляет собой объект типа `Arithm` я понятия не имею

2021-02-27 16:13 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +    }.get(name, Arithm)
> но это вроде не должно сильно на производительность влиять

Мы в python, конечно, но не в вакууме, память вполне реальная и не бесплатная, чтобы ее выделить и освободить интерпретатор делает довольно много действий
 
> Ифами - уродливо

Это очень субъективное суждение. Уверен, что многие с вами не согласятся.

2021-02-27 16:15 UTC, aleksZubakov commented on CLI/calls/calls.py
> +                                          peel=lambda s: s[2:-1])
Код от этого, к сожалению, читаемым не стал. Мб, даже стал более запутанным, но я не видел как было по-другому. 

Хотя бы распаковка с нормальными именами, и то будет лучше

2021-02-27 16:18 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            out += line
> Без честных потоков это сложно нормально сделать

[Тык](https://docs.python.org/3/library/io.html)

2021-02-27 16:19 UTC, aleksZubakov commented on CLI/calls/calls.py
> +        "echo": Echo,
> Он же маленький.

Посчитайте, пожалуйста, сколько такой объект в памяти займет, хорошее упражнение.

> Так же лучше выглядит с небольшим пенальти по производительности

Хотя бы вынесите его куда-нибудь, если у Вас такие проблемы с ифами)

2021-02-27 16:20 UTC, aleksZubakov commented on CLI/parser.py
> +    id : /[a-zA-Z][a-zA-Z0-9_]*/
но сейчас ее нет, но есть куча лишнего кода)

2021-02-27 16:23 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +        return mem, err
Вы не правильно меня поняли. Я говорю, что не нужно убирать возврат ошибки вообще, я говорю, что в _большинстве_ случаев это лишнее

2021-03-03 18:21 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +    }.get(name, Arithm)
Вынес его в поле класса

2021-03-03 18:21 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +    # return out
удалил

2021-03-03 18:21 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +        return self.__str__()
поправил

2021-03-03 18:21 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +        return mem, err
Непонятно что делать :(

2021-03-03 18:22 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +                file = open(arg, 'r')
поправил

2021-03-03 18:22 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            except Exception:
поправил

2021-03-03 18:22 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            lines = f.split('\n')
легаси, я поправил

2021-03-03 18:23 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +        if len(file_args) == 0 and err == "":
поправлено

2021-03-03 18:23 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +        "echo": Echo,
Вынес

2021-03-03 18:24 UTC, FrogOfJuly commented on CLI/cli.py
> +        line = line[:-1]
действительно

2021-03-03 18:24 UTC, FrogOfJuly commented on CLI/cli.py
> +        if line == "":
поправил

2021-03-03 18:26 UTC, FrogOfJuly commented on CLI/parser.py
> +    id : /[a-zA-Z][a-zA-Z0-9_]*/
Это overengineering. Просто если это задание разовъется, то это придется все равно добавлять. Сейчас это и правда лишний код

2021-03-03 18:27 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +        def perform_substitute(string: str, regexp, peel: Callable[[str], str]) -> str:
поправил

2021-03-03 18:30 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            var = peel(match[0])
Поправил

2021-03-03 18:30 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +                                          peel=lambda s: s[2:-1])
Поправил

2021-03-03 18:32 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            new_string = re.sub(regexp,
В какой цикл? Непонятно :(

2021-03-03 18:45 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            out += self.cat(arg)
Вроде поправил

2021-03-03 18:45 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            out += name + " : " + " ".join([str(r) for r in vals]) + "\n"
вроде поправил

2021-03-03 18:47 UTC, FrogOfJuly commented on CLI/arithm/arithm.py
> +class Arithm:
Если честно само название я от безысходности придумал, потому что другого имени для остальных команд вроде 
```
a=$(cat file.txt)
a=$((1 + 3))
```
я не придумал

2021-03-03 20:23 UTC, FrogOfJuly commented on CLI/calls/calls.py
> +            out += line
Сделал чере потоки и оно вроде работает

2021-03-23 23:55 UTC, aleksZubakov reviewed
- Сложные подстановки разъехались: 
```python
x=ec
y=ho
$x$y 50
```
- pipe не работает:
```python
echo text | cat
```
- Обычные подстановки тоже не работают:
```
x=10
echo 'asd$x'
```
- Внешние команды не работают:
```python
git log
trying to execute non-existing command : "Call: git ['log']" on input: None
```
-

2021-03-23 23:55 UTC, aleksZubakov commented on CLI/arithm/arithm.py
> +        return mem, err
Хотя бы None возвращать или что-то хитрее придумать, видимо

2021-03-23 23:55 UTC, aleksZubakov commented on CLI/calls/calls.py
> +    def filenames2files(filenames: List[str]) -> Generator[Tuple[Optional[TextIO], str], None, None]:
\>80 символов, не по PEP8 :(

2021-03-23 23:55 UTC, aleksZubakov commented on CLI/calls/calls.py
> +                file = open(arg, 'r')
Так они все еще все разом открываются

2021-03-23 23:55 UTC, aleksZubakov commented on CLI/calls/calls.py
> +            new_string = re.sub(regexp,
В цикл ниже, очевидно

2021-03-24 13:54 UTC, merged